springdoc:
  api-docs:
    path: /api-docs
server:
  port: 8082

# DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/berkertan
    username: berkertan
  security:
    user:
      password: berk123

  # Hibernate Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true